name: Build with Gradle

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Run Gradle build
      run: ./gradlew clean build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: adyeshach
        path: build/libs/*.jar
